### PR TITLE
Fix Duplicate Remote Projects Bug

### PR DESCRIPTION
**Pull request by santitigaga**
Fixed duplicate projects when the name of repository project not match.

### CODE REVIEW

**Comment by YoussefRaafatNasry** [comment]
Can you provide a test cast on how to recreate this bug?

**Comment by santitigaga** [comment]
imagen

Of course, I have recreated this error by setting a project with a typo in the project name. so, the for does not find this project however it has the last record and reprints the last project. 

imagen
 Regards

**Comment by YoussefRaafatNasry** [comment]
Thanks @santitigaga for fixing this!

**Comment by santitigaga** [comment]
> Thanks @santitigaga for fixing this!

Your Welcome

**Pull request merged**
